# Copyright 2021-2022, Collabora, Ltd.
# SPDX-License-Identifier: CC0-1.0

name: Android OpenXR-CTS - Release
on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  # CTS
  build-android-cts-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install ninja-build tool
        uses: seanmiddleditch/gha-setup-ninja@v3
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
          cache: gradle

      - name: Build OpenXR-CTS for Android
        run: |
          cd src/conformance
          ./gradlew clean && ./gradlew assembleRelease

      - name: Sign OpenXR-CTS Android release
        uses: r0adkll/sign-android-release@349ebdef58775b1e0d8099458af0816dc79b6407
        id: sign_cts
        with:
          releaseDirectory: src/conformance/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.APK_SIGNING_KEY }}
          alias: ${{ secrets.APK_ALIAS }}
          keyStorePassword: ${{ secrets.APK_KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.APK_KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "30.0.3"

      - name: Rename APK
        env:
          SIGNED_FILE: ${{ steps.sign_cts.outputs.signedReleaseFile }}
          TAGNAME: ${{ github.event.release.tag_name }}
        run: mv $SIGNED_FILE $TAGNAME.apk

      - name: Upload OpenXR-CTS Android
        uses: actions/upload-artifact@v2
        # if: startsWith(github.ref, 'refs/tags/')
        with:
          name: OpenXR-CTS Android
          path: ${{ github.event.release.tag_name }}.apk
      - name: Release
        uses: softprops/action-gh-release@v1
        # if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ github.event.release.tag_name }}.apk
