# Copyright 2021-2022, Collabora, Ltd.
# SPDX-License-Identifier: CC0-1.0

name: Windows CTS builds
on:
  workflow_call:
  workflow_dispatch:

jobs:
  # generate_matrix:
  #   runs-on: ubuntu-latest
  #   outputs:
  #     matrix: ${{ steps.set-matrix.outputs.matrix }}
  #   steps:
  #     - uses: actions/checkout@v3
  #     - id: set-matrix
  #       run: python3 .github/scripts/generate_windows_matrix_build.py matrix
  msvc-build:
    strategy:
      fail-fast: true
      matrix:
        preset:
          - win32
          - x64

    uses: "./.github/workflows/msvc-build-preset.yml"
    with:
      preset: "${{ matrix.preset }}"
      artifactName: "build_with_cts_${{ matrix.preset }}"
