# Copyright 2021-2023, Collabora, Ltd.
# SPDX-License-Identifier: CC0-1.0

name: Build Windows release artifacts
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  msvc-build:
    strategy:
      fail-fast: true
      matrix:
        preset:
          - win32
          - x64

    uses: "./.github/workflows/msvc-build-preset.yml"
    with:
      preset: "${{ matrix.preset }}"
      artifactName: "openxr-cts-${{ matrix.preset }}"
      buildType: "RelWithDebInfo"

